// Generated by Wrangler by running `wrangler types ./src/worker-types.d.ts -e local`

interface Env {
	FRONTEND_HOST: "localhost:5173" | "pub-27a25e5343e3486fb70b81dab7e05d7d.r2.dev";
	FRONTEND_PROTOCOL: "http:" | "https:";
	FRONTEND_PATH_PREFIX: "" | "/dev" | "/prod";
	GAME_CONTROLLER: DurableObjectNamespace /* GameController */;
}
